id = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]

[network_config]
mode = "router"
connect.endpoints = []
listen.endpoints = ["quic/[::]:4700"]

[network_config.transport]
unicast.max_links = 4
unicast.compression.enabled = true
[network_config.transport.link]
[network_config.transport.link.tls]
server_name_verification = false
root_ca_certificate = "config/cert/ca_cert.pem"
server_certificate = "config/cert/client_cert.pem"
server_private_key = "config/cert/client_key.pem"

[network_config.scouting]
gossip.enabled = false
multicast.enabled = false

[network_config.routing]
peer.mode = "peer_to_peer"
router.peers_failover_brokering = true
